# alexdavid/vim-min-git-status-test
FROM node:10.16.3-stretch

RUN apt-get update && apt-get install -y vim
RUN git config --global user.name "Test User"
RUN git config --global user.email "test@example.com"
